name = "AdaptiveArrayPools"
uuid = "4f381ef7-9af0-4cbe-99d4-cf36d7b0f233"
version = "0.1.0"
authors = ["Min-Gu Yoo <mgyoo86@gmail.com>"]

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
AdaptiveArrayPoolsCUDAExt = "CUDA"

[compat]
julia = "1.10"
Preferences = "1"
CUDA = "5"
