name = "AdaptiveArrayPools"
uuid = "5768322a-0810-4546-8322-123456789abc"
version = "0.1.1"
authors = ["Min-Gu Yoo <mgyoo86@gmail.com>"]

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Preferences = "1"
julia = "1.10"
