name = "AdaptiveArrayPools"
uuid = "5768322a-0810-4546-8322-123456789abc"
version = "0.2.5"
authors = ["Min-Gu Yoo <mgyoo86@gmail.com>"]

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
AdaptiveArrayPoolsCUDAExt = "CUDA"
